metadata_templates_repo: https://github.com/ScilifelabDataCentre/scilifelab-metadata-templates
metadata_templates_dest: "{{ sw_path }}/scilifelab-metadata-templates"
metadata_templates_version: 87a9174dbd0fb8725637d43cbfb76905bc6e02f6