---
taca_ngi_repo: https://github.com/NationalGenomicsInfrastructure/taca-ngi-pipeline.git
taca_ngi_dest: "{{ sw_path }}/taca-ngi-pipeline"
taca_ngi_version: 52dc51bca7f08c5a3dd8c308a036436af25d7f27

flowcell_parser_repo: https://github.com/NationalGenomicsInfrastructure/flowcell_parser.git
flowcell_parser_dest: "{{ sw_path }}/flowcell_parser"
flowcell_parser_version: 286b54825a83ef5cfed5345752f56b7e93265a1a

taca_repo: https://github.com/NationalGenomicsInfrastructure/TACA.git
taca_dest: "{{ sw_path }}/TACA"
taca_version: 764fe822cd5419d5c1a33b8cf222001084f2b59e

ngi_pipeline_analysisdir: "{{ ngi_pipeline_workdir }}/ANALYSIS"
ngi_pipeline_datadir: "{{ ngi_pipeline_workdir }}/DATA"
ngi_pipeline_deliverydir: "{{ ngi_pipeline_workdir }}/DELIVERY"
