
- name: create virtual python env for arteria-delivery
  shell: "conda create --name {{ arteria_service_name }} python=3.13"
  args:
    creates: "{{ arteria_service_env_root }}"

- name: get arteria-delivery from git
  git:
    repo: "{{ arteria_delivery_repo }}"
    dest: "{{ arteria_service_src_path }}"
    version: "{{ arteria_delivery_version }}"

- name: install arteria-delivery requirements
  pip:
    requirements: "{{ arteria_service_src_path }}/requirements/dev"
    chdir: "{{ arteria_service_src_path }}"
    executable: "{{ arteria_service_env_root }}/bin/pip"
    state: present

- name: install arteria-delivery
  pip:
    name: .
    chdir: "{{ arteria_service_src_path }}"
    executable: "{{ arteria_service_env_root }}/bin/pip"
    state: present
